import { getClientStorefrontConfig } from "@/lib/store-slug-client";

const spanishCopy = {
  openMenu: "Abrir menú",
  closeMenu: "Cerrar menú",
  openCart: "Abrir carrito",
  closeCart: "Cerrar carrito",
  cart: "Carrito",
  searchProducts: "Buscar productos...",
  search: "Buscar",
  searchDescription: "Nombre, descripción...",
  clearSearch: "Limpiar búsqueda",
  closeSearch: "Cerrar búsqueda",
  account: "Mi cuenta",
  signIn: "Ingresar",
  favorites: "Ver favoritos",
  emptyCart: "Tu carrito está vacío",
  emptyCartDescription: "Explorá el catálogo y encontrá tu próxima prenda favorita.",
  keepShopping: "Seguir comprando",
  viewProducts: "Ver productos",
  shippingAtCheckout: "Envío calculado en el checkout.",
  goToCheckout: "Ir al checkout",
  viewFullCart: "Ver carrito completo",
  removeFromCart: (name: string) => `Quitar ${name} del carrito`,
  each: "c/u",
  products: "Productos",
  productSingular: "producto",
  productPlural: "productos",
  catalogDescription: (store: string) => `Explorá el catálogo completo de ${store}.`,
  featuredDescription: "Selección destacada de la tienda.",
  resultsFor: (query: string) => `Resultados para “${query}”`,
  promotion: "Promoción",
  featured: "Destacados",
  category: "Categoría",
  all: "Todas",
  maxPrice: "Precio máximo",
  sort: "Ordenar",
  newest: "Más recientes",
  priceAsc: "Precio: menor a mayor",
  priceDesc: "Precio: mayor a menor",
  nameAsc: "Nombre A–Z",
  noImage: "Sin imagen",
  outOfStock: "Sin stock",
  cartSummary: "Resumen",
  shipping: "Envío",
  atCheckout: "En checkout",
  estimatedTotal: "Total estimado",
  checkoutAction: "Continuar al checkout",
  checkoutHint: "Pagá de forma segura con Mercado Pago",
  requestAction: "Consultar por este pedido",
  requestHint: "Coordinaremos personalización, entrega y pago antes de confirmar.",
  buyNow: "Comprar ahora",
  addToCart: "Agregar al carrito",
  added: "¡Agregado!",
  redirecting: "Redirigiendo...",
  cartItems: (count: number) => `${count} artículo${count === 1 ? "" : "s"} en tu pedido`,
  cartReview: "Revisá los productos antes de pagar.",
} as const;

const italianCopy = {
  openMenu: "Apri menu",
  closeMenu: "Chiudi menu",
  openCart: "Apri carrello",
  closeCart: "Chiudi carrello",
  cart: "Carrello",
  searchProducts: "Cerca creazioni...",
  search: "Cerca",
  searchDescription: "Nome, descrizione...",
  clearSearch: "Cancella ricerca",
  closeSearch: "Chiudi ricerca",
  account: "Il mio profilo",
  signIn: "Accedi",
  favorites: "Vedi preferiti",
  emptyCart: "Il tuo carrello è vuoto",
  emptyCartDescription: "Esplora la collezione e trova una creazione speciale.",
  keepShopping: "Continua lo shopping",
  viewProducts: "Vedi le creazioni",
  shippingAtCheckout: "Consegna da concordare prima dell'ordine.",
  goToCheckout: "Vai al riepilogo",
  viewFullCart: "Vedi tutto il carrello",
  removeFromCart: (name: string) => `Rimuovi ${name} dal carrello`,
  each: "cad.",
  products: "Creazioni",
  productSingular: "creazione",
  productPlural: "creazioni",
  catalogDescription: (store: string) => `Esplora la collezione completa di ${store}.`,
  featuredDescription: "Una selezione di creazioni in evidenza.",
  resultsFor: (query: string) => `Risultati per “${query}”`,
  promotion: "Selezione",
  featured: "In evidenza",
  category: "Categoria",
  all: "Tutte",
  maxPrice: "Prezzo massimo",
  sort: "Ordina",
  newest: "Più recenti",
  priceAsc: "Prezzo: dal più basso",
  priceDesc: "Prezzo: dal più alto",
  nameAsc: "Nome A–Z",
  noImage: "Senza immagine",
  outOfStock: "Non disponibile",
  cartSummary: "Riepilogo",
  shipping: "Consegna",
  atCheckout: "Da concordare",
  estimatedTotal: "Totale indicativo",
  checkoutAction: "Continua al pagamento",
  checkoutHint: "Pagamento sicuro",
  requestAction: "Richiedi questo ordine",
  requestHint: "Confermeremo personalizzazione, consegna e pagamento prima dell'ordine.",
  buyNow: "Richiedi ora",
  addToCart: "Aggiungi al carrello",
  added: "Aggiunto!",
  redirecting: "Apertura...",
  cartItems: (count: number) => `${count} ${count === 1 ? "creazione" : "creazioni"} nella richiesta`,
  cartReview: "Controlla le creazioni prima di inviare la richiesta.",
};

export function getStorefrontCopy() {
  return getClientStorefrontConfig().locale === "it-IT"
    ? italianCopy
    : spanishCopy;
}
